
version: '3.8'

services:

  todoDB:
    image: mysql:8.0
    container_name: todoDB
    volumes:
      - ./database/todos.init.sql:/docker-entrypoint-initdb.d/todos.init.sql
      - ./database/users.init.sql:/docker-entrypoint-initdb.d/users.init.sql
      - ./database/todos_testing.init.sql:/docker-entrypoint-initdb.d/todos_testing.init.sql
      - ./database/users_testing.init.sql:/docker-entrypoint-initdb.d/users_testing.init.sql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "todo_app"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "3340:3306"

  adminer:
    image: adminer:4.8.1
    container_name: todoDBAdminer
    ports:
      - 8090:8080

    depends_on:
      - todoDB
    